<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $productos = [
            [
                'idcategoria' => 1,
                'codigo' => 'LIB001',
                'nombre' => 'Libros de autoayuda',
                'stock' => 0,
                'descripcion' => 'Literatura que ofrece consejos y técnicas para el crecimiento personal y el bienestar.',
                'precio_venta' => 20,
            ],
            [
                'idcategoria' => 1,
                'codigo' => 'LIB002',
                'nombre' => 'Libros de cocina',
                'stock' => 0,
                'descripcion' => 'Publicaciones con recetas y técnicas culinarias para diferentes tipos de cocina.',
                'precio_venta' => 5,
            ],
            [
                'idcategoria' => 1,
                'codigo' => 'LIB003',
                'nombre' => 'Revistas de moda',
                'stock' => 0,
                'descripcion' => 'Revistas especializadas en tendencias de moda, belleza y estilo de vida.',
                'precio_venta' => 5,
            ],
            [
                'idcategoria' => 1,
                'codigo' => 'LIB004',
                'nombre' => 'Agendas y planificadores',
                'stock' => 0,
                'descripcion' => 'Cuadernos con páginas para organizar tareas, citas y eventos.',
                'precio_venta' => 15,
            ],
            [
                'idcategoria' => 7,
                'codigo' => 'PAP001',
                'nombre' => 'Papel decorativo',
                'stock' => 0,
                'descripcion' => 'Papel con diseños y estampados utilizados para manualidades y decoración.',
                'precio_venta' => 3.5,
            ],
            [
                'idcategoria' => 7,
                'codigo' => 'PAP002',
                'nombre' => 'Papel de regalo',
                'stock' => 0,
                'descripcion' => 'Papel decorativo utilizado para envolver regalos.',
                'precio_venta' => 1.5,
            ],
            [
                'idcategoria' => 7,
                'codigo' => 'PAP003',
                'nombre' => 'Papeles adhesivos',
                'stock' => 0,
                'descripcion' => 'Hojas de papel con adhesivo en la parte posterior para pegar y etiquetar objetos.',
                'precio_venta' => 5,
            ],
            [
                'idcategoria' => 7,
                'codigo' => 'PAP004',
                'nombre' => 'Adhesivos decorativos',
                'stock' => 0,
                'descripcion' => 'Pegatinas con diseños diversos para decorar objetos y papelería.',
                'precio_venta' => 8,
            ],
            [
                'idcategoria' => 7,
                'codigo' => 'PAP005',
                'nombre' => 'Pegatinas para scrapbooking',
                'stock' => 0,
                'descripcion' => 'Adhesivos decorativos utilizados en la técnica de scrapbooking.',
                'precio_venta' => 6,
            ],
            [
                'idcategoria' => 7,
                'codigo' => 'PAP006',
                'nombre' => 'Pegatinas fluorescentes',
                'stock' => 0,
                'descripcion' => 'Adhesivos de colores llamativos utilizados para resaltar información en libros y documentos.',
                'precio_venta' => 6,
            ],
            [
                'idcategoria' => 7,
                'codigo' => 'COL001',
                'nombre' => 'Marcadores fluorescentes',
                'stock' => 0,
                'descripcion' => 'Rotuladores de colores vibrantes para resaltar información en libros y documentos.',
                'precio_venta' => 18,
            ],
            [
                'idcategoria' => 8,
                'codigo' => 'COL002',
                'nombre' => 'Cajas de lápices',
                'stock' => 0,
                'descripcion' => 'Contenedores para almacenar y organizar lápices de colores o de escribir.',
                'precio_venta' => 18,
            ],
            [
                'idcategoria' => 8,
                'codigo' => 'COL003',
                'nombre' => 'Set de lápices de colores',
                'stock' => 0,
                'descripcion' => 'Conjunto de lápices de colores variados para actividades artísticas y dibujo.',
                'precio_venta' => 20,
            ],
            [
                'idcategoria' => 8,
                'codigo' => 'COL004',
                'nombre' => 'Cajas de lápices de 24',
                'stock' => 0,
                'descripcion' => 'Contenedores para almacenar y organizar lápices de colores o de escribir.',
                'precio_venta' => 30,
            ],
            [
                'idcategoria' => 8,
                'codigo' => 'COL005',
                'nombre' => 'Lápices de grafito',
                'stock' => 0,
                'descripcion' => 'Lápices utilizados para escribir y dibujar con mina de grafito.',
                'precio_venta' => 3,
            ],
            [
                'idcategoria' => 8,
                'codigo' => 'COL006',
                'nombre' => 'Plumas estilográficas',
                'stock' => 0,
                'descripcion' => 'Instrumentos de escritura con punta de plumilla que utiliza tinta líquida.',
                'precio_venta' => 35,
            ],
            [
                'idcategoria' => 8,
                'codigo' => 'COL007',
                'nombre' => 'Portaminas',
                'stock' => 0,
                'descripcion' => 'Lápices mecánicos que utilizan minas delgadas para escribir o dibujar.',
                'precio_venta' => 3.5,
            ],
            [
                'idcategoria' => 8,
                'codigo' => 'COL008',
                'nombre' => 'Lápices de carpintero',
                'stock' => 0,
                'descripcion' => 'Lápices utilizados en trabajos de carpintería para marcar y medir.',
                'precio_venta' => 5,
            ],
            [
                'idcategoria' => 8,
                'codigo' => 'COL009',
                'nombre' => 'Sellos de tinta',
                'stock' => 0,
                'descripcion' => 'Utensilios con diseños estampados para decorar papel y tarjetas.',
                'precio_venta' => 15,
            ],
            [
                'idcategoria' => 8,
                'codigo' => 'COL010',
                'nombre' => 'Bolígrafos de gel',
                'stock' => 0,
                'descripcion' => 'Bolígrafos con tinta en gel que proporcionan una escritura suave y vibrante.',
                'precio_venta' => 3,
            ],
            [
                'idcategoria' => 8,
                'codigo' => 'COL011',
                'nombre' => 'Marcadores de pizarra',
                'stock' => 0,
                'descripcion' => 'Rotuladores especiales para escribir y dibujar en pizarras blancas o de tiza.',
                'precio_venta' => 5,
            ],
            [
                'idcategoria' => 3,
                'codigo' => 'ESC001',
                'nombre' => 'Perforadoras de papel',
                'stock' => 0,
                'descripcion' => 'Herramientas utilizadas para hacer agujeros en papel y documentos.',
                'precio_venta' => 18,
            ],
            [
                'idcategoria' => 3,
                'codigo' => 'ESC002',
                'nombre' => 'Gomas de borrar',
                'stock' => 0,
                'descripcion' => 'Elementos utilizados para eliminar trazos de lápiz en papel.',
                'precio_venta' => 3,
            ],
            [
                'idcategoria' => 3,
                'codigo' => 'ESC003',
                'nombre' => 'Pegamento en barra mediano',
                'stock' => 0,
                'descripcion' => 'Adhesivo sólido en forma de barra para pegar papel y otros materiales.',
                'precio_venta' => 12,
            ],
            [
                'idcategoria' => 3,
                'codigo' => 'ESC004',
                'nombre' => 'Tijeras de manualidades',
                'stock' => 0,
                'descripcion' => 'Tijeras con hojas de diferentes formas para trabajos de artesanía y recortes.',
                'precio_venta' => 10,
            ],
            [
                'idcategoria' => 3,
                'codigo' => 'ESC005',
                'nombre' => 'Pegamento en barra',
                'stock' => 0,
                'descripcion' => 'Adhesivo sólido en forma de barra para pegar papel y otros materiales.',
                'precio_venta' => 6,
            ],
            [
                'idcategoria' => 3,
                'codigo' => 'ESC006',
                'nombre' => 'Borradores',
                'stock' => 0,
                'descripcion' => 'Elementos utilizados para borrar trazos de lápiz en papel.',
                'precio_venta' => 1,
            ],
            [
                'idcategoria' => 3,
                'codigo' => 'ESC007',
                'nombre' => 'Gomas de borrar',
                'stock' => 0,
                'descripcion' => 'Elementos utilizados para eliminar trazos de lápiz en papel.',
                'precio_venta' => 1,
            ],
            [
                'idcategoria' => 3,
                'codigo' => 'ESC008',
                'nombre' => 'Afiladores de lápices',
                'stock' => 0,
                'descripcion' => 'Utensilios utilizados para afilar puntas de lápices y portaminas.',
                'precio_venta' => 15,
            ],
            [
                'idcategoria' => 14,
                'codigo' => 'OFI001',
                'nombre' => 'Carpetas de archivos',
                'stock' => 0,
                'descripcion' => 'Folios con solapas utilizados para almacenar y organizar documentos.',
                'precio_venta' => 5,
            ],
            [
                'idcategoria' => 14,
                'codigo' => 'OFI002',
                'nombre' => 'Portafolios',
                'stock' => 0,
                'descripcion' => 'Carpeta con cierre utilizada para transportar y proteger documentos y papeles importantes.',
                'precio_venta' => 25,
            ],
            [
                'idcategoria' => 14,
                'codigo' => 'OFI003',
                'nombre' => 'Estuches de maquillaje',
                'stock' => 0,
                'descripcion' => 'Contenedores para organizar y transportar productos de maquillaje.',
                'precio_venta' => 35,
            ],
            [
                'idcategoria' => 14,
                'codigo' => 'OFI004',
                'nombre' => 'Cajas de almacenamiento',
                'stock' => 0,
                'descripcion' => 'Cajas de diferentes tamaños y materiales para guardar y organizar objetos.',
                'precio_venta' => 35,
            ],
            [
                'idcategoria' => 14,
                'codigo' => 'OFI005',
                'nombre' => 'Papeleras',
                'stock' => 0,
                'descripcion' => 'Recipientes para desechar papel y otros desechos en el hogar u oficina.',
                'precio_venta' => 35,
            ],
            [
                'idcategoria' => 14,
                'codigo' => 'OFI006',
                'nombre' => 'Revisteros',
                'stock' => 0,
                'descripcion' => 'Soportes para organizar y mostrar revistas y periódicos.',
                'precio_venta' => 25,
            ],
            [
                'idcategoria' => 14,
                'codigo' => 'OFI007',
                'nombre' => 'Lámparas de escritorio',
                'stock' => 0,
                'descripcion' => 'Lámparas diseñadas para iluminar el área de trabajo en escritorios.',
                'precio_venta' => 30,
            ],
            [
                'idcategoria' => 14,
                'codigo' => 'OFI008',
                'nombre' => 'Estuches de pinturas',
                'stock' => 0,
                'descripcion' => 'Cajas o bolsas para almacenar y transportar pinturas de diversos tipos.',
                'precio_venta' => 35,
            ],
            [
                'idcategoria' => 17,
                'codigo' => 'CUA001',
                'nombre' => 'Bloc de notas',
                'stock' => 0,
                'descripcion' => 'Cuaderno pequeño con hojas adhesivas para tomar notas y recordatorios.',
                'precio_venta' => 12,
            ],
            [
                'idcategoria' => 9,
                'codigo' => 'MAT000',
                'nombre' => 'Regla1',
                'stock' => 0,
                'descripcion' => 'Instrumentos de medición rectos utilizados para trazar líneas rectas.',
                'precio_venta' => 6,
            ],
            [
                'idcategoria' => 9,
                'codigo' => 'MAT002',
                'nombre' => 'Cintas métricas',
                'stock' => 0,
                'descripcion' => 'Herramientas de medición flexibles utilizadas en trabajos de costura y manualidades.',
                'precio_venta' => 2.5,
            ],
            [
                'idcategoria' => 9,
                'codigo' => 'MAT003',
                'nombre' => 'Reglas metalica',
                'stock' => 0,
                'descripcion' => 'Instrumentos de medición rectos utilizados para trazar líneas rectas.',
                'precio_venta' => 6,
            ],
            [
                'idcategoria' => 4,
                'codigo' => 'ART001',
                'nombre' => 'Álbumes de fotos',
                'stock' => 0,
                'descripcion' => 'Libros para guardar fotografías y crear álbumes de recuerdos.',
                'precio_venta' => 25,
            ],
            [
                'idcategoria' => 4,
                'codigo' => 'ART002',
                'nombre' => 'Globos de fiesta',
                'stock' => 0,
                'descripcion' => 'Globos de colores para decorar fiestas y celebraciones.',
                'precio_venta' => 10,
            ],
            [
                'idcategoria' => 4,
                'codigo' => 'ART003',
                'nombre' => 'Cajas de regalo',
                'stock' => 0,
                'descripcion' => 'Cajas decorativas utilizadas para presentar regalos de manera elegante.',
                'precio_venta' => 10,
            ],
            [
                'idcategoria' => 4,
                'codigo' => 'ART004',
                'nombre' => 'Marcos de fotos',
                'stock' => 0,
                'descripcion' => 'Estructuras para enmarcar y exhibir fotografías.',
                'precio_venta' => 25,
            ],
        ];


        foreach ($productos as $producto) {
            Category::create($producto);
        }

    }
}
